In [4]:
!pip install tensorflow matplotlib pandas scikit-learn

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/ed/b6/62345568cd07de5d9254fcf64d7e44aacbb6abde11ea953b3cb320e58d19/tensorflow-2.17.0-cp311-cp311-win_amd64.whl.metadata
  Using cached tensorflow-2.17.0-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
  Obtaining dependency information for tensorflow-intel==2.17.0 from https://files.pythonhosted.org/packages/66/03/5c447feceb72f5a38ac2aa79d306fa5b5772f982c2b480c1329c7e382900/tensorflow_intel-2.17.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>

In [108]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [109]:
df_start = pd.read_csv("turkish_toxic_language.csv",sep=',')

In [110]:
df_start.head()

text     target  source  \
0  Phil Spector bir lanet katil olduğunu Biliyors...     INSULT  jigsaw   
1  Lan siktirin gidin AMK pozitif sik kafaları Ül...  PROFANITY    told   
2  2pac Olmak İstiyorum Ja Rule bir Tupac Shakur ...      OTHER  jigsaw   
3  Ne yapılması gerekiyor Aradan sonra bu sayfaya...      OTHER  jigsaw   
4  Kabul Dream Chaser programı ile ilgili olmayan...      OTHER  jigsaw   

   is_toxic  
0         1  
1         1  
2         0  
3         0  
4         0

In [111]:
df_start.drop('source',axis=1, inplace=True)

In [112]:
df = pd.get_dummies(df_start, columns= ['target'],dtype=int)

In [113]:
df.head(10)

text  is_toxic  target_INSULT  \
0  Phil Spector bir lanet katil olduğunu Biliyors...         1              1   
1  Lan siktirin gidin AMK pozitif sik kafaları Ül...         1              0   
2  2pac Olmak İstiyorum Ja Rule bir Tupac Shakur ...         0              0   
3  Ne yapılması gerekiyor Aradan sonra bu sayfaya...         0              0   
4  Kabul Dream Chaser programı ile ilgili olmayan...         0              0   
5  Thanx Teşekkürler Bay horoz Bana son bir şans ...         0              0   
6  yarının başında istatistikleri alt üst eden Er...         1              0   
7  Kim söyledi bunu bana Yıkıcı yaptığım şeylerde...         1              1   
8  amını yolunu siktimin çocuğu support beğenmiyo...         1              0   
9                Zeka yaşı falan da orası ayrı sjsjd         1              1   

   target_OTHER  target_PROFANITY  target_RACIST  target_SEXIST  
0             0                 0              0              0  
1             0                 1              0              0  
2             1                 0              0              0  
3             1                 0              0              0  
4             1                 0              0              0  
5             1                 0              0              0  
6             0                 1              0              0  
7             0                 0              0              0  
8             0                 1              0              0  
9             0                 0              0              0

In [114]:
df.iloc[0]['text']

'Phil Spector bir lanet katil olduğunu Biliyorsun ve ben de tıpkı OJ gibi Onun oğlu falan mısın'

In [115]:
df.iloc[1]['text']

'Lan siktirin gidin AMK pozitif sik kafaları Ülkenin anası dikildi millet açlıktan sınanıyor siz daha slak salak herşey yoluna girecek gibi millete boş motivasyon aşılıyorsunuz'

In [116]:
df.iloc[3]['text']

'Ne yapılması gerekiyor Aradan sonra bu sayfaya baktığımda birkaç şey görüyorum Kölelik ve din ya da Din ve kölelik makalesi olmalı Makale kutsal metinlere odaklanıyor ancak makale din ile ilgili Başlık din ise bölümler Hıristiyanlık Yahudilik ve İslam olmalıdır Aksi takdirde makale yeniden adlandırılmalı İbrahimî kutsal yazılarda kölelik Yeni Ahit teki kadar çok iş gerekiyor ki hiçbir şey kalmayacağı için onu çıkarmak istemiyorum Bence bir NPOV etiketine sahip olmalı Düşünceler'

In [117]:
df.loc[(df['is_toxic'] == 1) & (df['target_OTHER'] == 1)]

Empty DataFrame
Columns: [text, is_toxic, target_INSULT, target_OTHER, target_PROFANITY, target_RACIST, target_SEXIST]
Index: []

In [118]:
df.drop(['is_toxic','target_OTHER'],axis=1, inplace=True)

In [119]:
df

text  target_INSULT  \
0      Phil Spector bir lanet katil olduğunu Biliyors...              1   
1      Lan siktirin gidin AMK pozitif sik kafaları Ül...              0   
2      2pac Olmak İstiyorum Ja Rule bir Tupac Shakur ...              0   
3      Ne yapılması gerekiyor Aradan sonra bu sayfaya...              0   
4      Kabul Dream Chaser programı ile ilgili olmayan...              0   
...                                                  ...            ...   
77795  İsmi kısaltmak için her kutu kendi başına bir ...              0   
77796  ecek acak 31 marta kadar incelenir gorusulur d...              0   
77797  Oh adamım Sen sadece yumuşak bir ineğin Birkaç...              1   
77798  Bu zayıf siteyi temizleyeceğim hyyuyuyuyuyuyuy...              1   
77799  Amanda aman putin 2036 ya kadar sen sabaha çık...              1   

       target_PROFANITY  target_RACIST  target_SEXIST  
0                     0              0              0  
1                     1              0              0  
2                     0              0              0  
3                     0              0              0  
4                     0              0              0  
...                 ...            ...            ...  
77795                 0              0              0  
77796                 0              0              0  
77797                 0              0              0  
77798                 0              0              0  
77799                 0              0              0  

[77800 rows x 5 columns]

In [120]:
df = df.rename(columns = {'target_INSULT': 'INSULT', 'target_PROFANITY': 'PROFANITY' , 'target_RACIST':'RACIST','target_SEXIST':'SEXIST'})

In [121]:
df

text  INSULT  PROFANITY  \
0      Phil Spector bir lanet katil olduğunu Biliyors...       1          0   
1      Lan siktirin gidin AMK pozitif sik kafaları Ül...       0          1   
2      2pac Olmak İstiyorum Ja Rule bir Tupac Shakur ...       0          0   
3      Ne yapılması gerekiyor Aradan sonra bu sayfaya...       0          0   
4      Kabul Dream Chaser programı ile ilgili olmayan...       0          0   
...                                                  ...     ...        ...   
77795  İsmi kısaltmak için her kutu kendi başına bir ...       0          0   
77796  ecek acak 31 marta kadar incelenir gorusulur d...       0          0   
77797  Oh adamım Sen sadece yumuşak bir ineğin Birkaç...       1          0   
77798  Bu zayıf siteyi temizleyeceğim hyyuyuyuyuyuyuy...       1          0   
77799  Amanda aman putin 2036 ya kadar sen sabaha çık...       1          0   

       RACIST  SEXIST  
0           0       0  
1           0       0  
2           0       0  
3           0       0  
4           0       0  
...       ...     ...  
77795       0       0  
77796       0       0  
77797       0       0  
77798       0       0  
77799       0       0  

[77800 rows x 5 columns]

In [122]:
from tensorflow.keras.layers import TextVectorization

In [123]:
df.columns

Index(['text', 'INSULT', 'PROFANITY', 'RACIST', 'SEXIST'], dtype='object')

In [124]:
X = df['text']
y = df[df.columns[1:]].values

In [125]:
MAX_FEATURES = 200000 

In [126]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                               output_sequence_length = 1800,
                               output_mode = 'int')

In [127]:
vectorizer.adapt(X.values)

In [128]:
vectorized_text = vectorizer(X.values)

In [129]:
vectorizer('Phil')

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([7562,    0,    0, ...,    0,    0,    0], dtype=int64)>

In [130]:
vectorized_text

<tf.Tensor: shape=(77800, 1800), dtype=int64, numpy=
array([[  7562, 122962,      2, ...,      0,      0,      0],
       [   206,   2550,    589, ...,      0,      0,      0],
       [ 36230,    130,  27118, ...,      0,      0,      0],
       ...,
       [   496,   2460,     28, ...,      0,      0,      0],
       [     4,   1628,   3391, ...,      0,      0,      0],
       [ 24082,   2400,   2445, ...,      0,      0,      0]], dtype=int64)>

In [131]:
#MCSHBAP - map, chache, shuffle, batch, prefetch  from_tensor_slices, list_file
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) # helps bottlenecks

In [132]:
type(dataset)

tensorflow.python.data.ops.prefetch_op._PrefetchDataset

In [133]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [144]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [145]:
model = Sequential()
# Create the embedding layer 
model.add(Embedding(MAX_FEATURES+1, 32))
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(32, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
# Final layer 
model.add(Dense(4, activation='sigmoid'))

In [146]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')

In [147]:
y[0]

array([1, 0, 0, 0])

In [148]:
history = model.fit(train, epochs=1, validation_data=val)

3404/3404 ━━━━━━━━━━━━━━━━━━━━ 1645s 482ms/step - loss: 0.2582 - val_loss: 0.1040
